language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements/dev.txt -i https://pypi.org/simple/
script:
  - flask translate compile && pytest
  - curl -s https://codecov.io/bash | bash
