language: python
python:
- 3.7.5
- '3.8'
- '3.9'
install:
- pip install -r requirements-dev.txt
script:
- flask translate compile && pytest
- curl -s https://codecov.io/bash | bash
deploy:
  provider: heroku
  api_key:
    secure: wZqrVjTA0d92FY4hTDldpA/8B1sCeXgeA5MoWwTNbvh2C1jKgINDu7F09nNf7NvXrN4pseeBUXgeBDbQzkGRG1EYPGTCVbzej9TnfPcsndUKn+9ruJpdxlCpRL3hdjTLIsubHdj9eamQaMMhlt5lalTmFNKQ3jGiUI2cEGZ74Vd3FPEndM7JrAmkb54lft/wF4pegTkL61QjbLWDTlhoCjj9l668yJnL3eIi5XkgnkyVW4j5iIUmNOKMyV7LGQ/nUhd+3NlGNPxZBFoY+D+PELQnmDb+tQBu4p2ILoa20hPfUYUo9zcvASKWhV9rxhbJrKa8UM3mJp/Yiel/GqHc9Ev0JBlzNAtUTFlEpVPOyGMoxHic5R/NbUrReFvW2xj4sHHTMXKozo4c3hn2m8OnTSLg/M95q38s4c6Bf6Zu+Ba1ldJPaJTh6O7t/ibkEy/X9ChitQuqSwnmDzD7rURArRsmoe0gp5vBxLoI1a34f2pugqPJW9mQTaULuzrxy6yQYfaOA07hvZ0Q/11NYwzcI1qrBZoIvCdWipRR9CYpykSlXXYUb5F1dtPDaA60zAptc2tZxN6qpGZUFe5iggZjaIu8aIlcOIRgGU0lkymztbsIz9luzzhCu2LcNcoadY/ZDAtKuCGWxufCLYwfKZHR88FE+PNGY/qOtwjA3l6olps=
  app: flog-web
  run: flask deploy
  on:
    python: 3.9
