"""empty message

Revision ID: 0a8453c4d88c
Revises: d9357025b879
Create Date: 2022-01-21 16:46:37.092273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8453c4d88c'
down_revision = 'd9357025b879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clicks_today', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clicks_today')
        batch_op.drop_column('clicks')

    # ### end Alembic commands ###
