"""add field picked to post

Revision ID: 1582919e9c92
Revises: 5a7ba0146ee5
Create Date: 2021-07-01 10:39:34.720875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1582919e9c92'
down_revision = '5a7ba0146ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picked')
    # ### end Alembic commands ###
