"""Add Column can_be_seen_by_others to model Post

Revision ID: 172ca3e17c2a
Revises: aefa596e7114
Create Date: 2020-10-18 20:26:20.223082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "172ca3e17c2a"
down_revision = "aefa596e7114"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post", sa.Column("can_be_seen_by_others", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "can_be_seen_by_others")
    # ### end Alembic commands ###
