"""Add slugs

Revision ID: 1847ae7ae587
Revises: 3ad34cb27e3f
Create Date: 2020-08-25 17:56:49.618105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1847ae7ae587"
down_revision = "3ad34cb27e3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_articles_timestamp", table_name="articles")
    op.drop_index("ix_articles_title", table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=64), nullable=True),
        sa.Column("author_id", sa.INTEGER(), nullable=True),
        sa.Column("date", sa.VARCHAR(length=64), nullable=True),
        sa.Column("content", sa.TEXT(length=2048), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_articles_title", "articles", ["title"], unique=False)
    op.create_index("ix_articles_timestamp", "articles", ["timestamp"], unique=False)
    # ### end Alembic commands ###
