"""empty message

Revision ID: 30ce011500f9
Revises: ca6d02539ab5
Create Date: 2022-01-24 11:38:59.921048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30ce011500f9'
down_revision = 'ca6d02539ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alpha_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_update')
        batch_op.drop_column('alpha_index')

    # ### end Alembic commands ###
