"""Change table name

Revision ID: 329b29fae865
Revises: eba13c37bbf0
Create Date: 2020-08-07 10:46:42.784856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "329b29fae865"
down_revision = "eba13c37bbf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
