"""Change comments to feedback for future use

Revision ID: 3ad34cb27e3f
Revises: 329b29fae865
Create Date: 2020-08-15 15:04:45.110599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3ad34cb27e3f"
down_revision = "329b29fae865"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
