"""Remove uniqueness check for post slugs

Revision ID: 5c9c64efc276
Revises: f497cb532a67
Create Date: 2020-11-15 10:11:41.600901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c9c64efc276"
down_revision = "f497cb532a67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("slug", table_name="post")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("slug", "post", ["slug"], unique=True)
    # ### end Alembic commands ###
