"""Add field timestamp to column

Revision ID: 5caf2aefd50a
Revises: 7c53bb2bbf74
Create Date: 2021-02-19 08:57:23.614964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5caf2aefd50a"
down_revision = "7c53bb2bbf74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("column", sa.Column("timestamp", sa.DateTime(), nullable=True))
    op.drop_constraint("post_ibfk_2", "post", type_="foreignkey")
    op.drop_column("post", "column_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column(
            "column_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key("post_ibfk_2", "post", "column", ["column_id"], ["id"])
    op.drop_column("column", "timestamp")
    # ### end Alembic commands ###
