"""Add column

Revision ID: 61a597d621ef
Revises: 8192b68b7bd0
Create Date: 2021-02-17 12:34:33.379669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61a597d621ef"
down_revision = "8192b68b7bd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "column",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("post", sa.Column("column_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "post", "column", ["column_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_column("post", "column_id")
    op.drop_table("column")
    # ### end Alembic commands ###
