"""Add uniqueness check for group name

Revision ID: 620fddf625cd
Revises: 64bdf1198e2e
Create Date: 2021-01-01 13:01:43.103178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "620fddf625cd"
down_revision = "64bdf1198e2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "group", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="unique")
    # ### end Alembic commands ###
