"""Add group manager field

Revision ID: 64bdf1198e2e
Revises: 04e9bf2293c1
Create Date: 2020-12-31 21:40:21.821953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64bdf1198e2e"
down_revision = "04e9bf2293c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("manager_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "group", "user", ["manager_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group", type_="foreignkey")
    op.drop_column("group", "manager_id")
    # ### end Alembic commands ###
