"""Remove field post_id and post relationship from model Image

Revision ID: 66997fab6cc0
Revises: e483ba67363b
Create Date: 2020-12-12 19:41:45.614511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "66997fab6cc0"
down_revision = "e483ba67363b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("private", sa.Boolean(), nullable=True))
    op.drop_constraint("image_ibfk_2", "image", type_="foreignkey")
    op.drop_column("image", "post_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image",
        sa.Column(
            "post_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key("image_ibfk_2", "image", "post", ["post_id"], ["id"])
    op.drop_column("image", "private")
    # ### end Alembic commands ###
