"""add message

Revision ID: 789ac8c2844f
Revises: 4679239b5c6a
Create Date: 2021-06-06 09:27:18.711529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "789ac8c2844f"
down_revision = "4679239b5c6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_timestamp"), "message", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_timestamp"), table_name="message")
    op.drop_table("message")
    # ### end Alembic commands ###
