"""Change field Post.column to Post.columns

Revision ID: 7c53bb2bbf74
Revises: 61a597d621ef
Create Date: 2021-02-18 18:12:53.885069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7c53bb2bbf74"
down_revision = "61a597d621ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "column_post",
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("column_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["column_id"],
            ["column.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
    )
    op.drop_constraint("post_ibfk_2", "post", type_="foreignkey")
    op.drop_column("post", "column_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column(
            "column_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key("post_ibfk_2", "post", "column", ["column_id"], ["id"])
    op.drop_table("column_post")
    # ### end Alembic commands ###
