"""Add relationships between users and feedbacks

Revision ID: 911cc5d772fc
Revises: 1847ae7ae587
Create Date: 2020-08-30 12:55:15.062295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911cc5d772fc'
down_revision = '1847ae7ae587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'user', ['author_id'], ['id'])
    op.drop_column('feedback', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('author', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'author_id')
    # ### end Alembic commands ###
