"""add private column to group

Revision ID: 9612aba86eb2
Revises: 789ac8c2844f
Create Date: 2021-06-06 10:31:28.453405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9612aba86eb2"
down_revision = "789ac8c2844f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("private", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "private")
    # ### end Alembic commands ###
