"""Add blocked user

Revision ID: a594303c45a5
Revises: 620fddf625cd
Create Date: 2021-01-15 12:29:32.350188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a594303c45a5"
down_revision = "620fddf625cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("blocked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "blocked")
    # ### end Alembic commands ###
