"""Change column 'can_be_seen_by_others' name to 'private'

Revision ID: aafd15767fb7
Revises: 172ca3e17c2a
Create Date: 2020-10-20 20:48:26.370514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafd15767fb7'
down_revision = '172ca3e17c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('private', sa.Boolean(), nullable=True))
    op.drop_column('post', 'can_be_seen_by_others')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', sa.Column('can_be_seen_by_others', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('post', 'private')
    # ### end Alembic commands ###
