"""add ai into columns

Revision ID: ca6d02539ab5
Revises: 0a8453c4d88c
Create Date: 2022-01-24 10:35:02.869970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ca6d02539ab5"
down_revision = "0a8453c4d88c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alpha_index", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_update", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
