"""add ai into columns

Revision ID: ca6d02539ab5
Revises: 0a8453c4d88c
Create Date: 2022-01-24 10:35:02.869970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ca6d02539ab5"
down_revision = "0a8453c4d88c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alpha_index", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_update", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_update")
        batch_op.drop_column("alpha_index")

    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("author", mysql.VARCHAR(length=20), nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")

    op.create_table(
        "articles",
        sa.Column("title", mysql.VARCHAR(length=64), nullable=True),
        sa.Column("author", mysql.VARCHAR(length=64), nullable=True),
        sa.Column("date", mysql.VARCHAR(length=64), nullable=True),
        sa.Column("content", mysql.TEXT(), nullable=True),
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("timestamp", mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index("ix_articles_title", ["title"], unique=False)
        batch_op.create_index("ix_articles_timestamp", ["timestamp"], unique=False)

    # ### end Alembic commands ###
