"""add column topping

Revision ID: cf2cec8755ae
Revises: 1582919e9c92
Create Date: 2021-07-11 16:28:28.169774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf2cec8755ae"
down_revision = "1582919e9c92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("column", sa.Column("topped", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("column", "topped")
    # ### end Alembic commands ###
