"""Add coins

Revision ID: dd62dd1cc018
Revises: cf2cec8755ae
Create Date: 2021-08-18 14:42:00.096177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd62dd1cc018'
down_revision = 'cf2cec8755ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_table',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    op.add_column('user', sa.Column('coins', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_table')
    op.drop_column('user', 'coins')
    # ### end Alembic commands ###
