"""add default user status

Revision ID: e4495d44cf0a
Revises: d8694aedfc5f
Create Date: 2022-03-18 19:47:06.597285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4495d44cf0a'
down_revision = 'd8694aedfc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_status', sa.String(64), default="online", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_status')
    # ### end Alembic commands ###
