"""Add model Image

Revision ID: e483ba67363b
Revises: d7252fd285bd
Create Date: 2020-12-12 19:32:45.452507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e483ba67363b"
down_revision = "d7252fd285bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("image")
    # ### end Alembic commands ###
