"""Add Feedback

Revision ID: eba13c37bbf0
Revises: 597e79657a6d
Create Date: 2020-08-04 16:23:24.102806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eba13c37bbf0"
down_revision = "597e79657a6d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
