name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ matrix.os }}-pip-
            ${{ matrix.os }}-
      - name: Install dependencies
        run: |
          pip3 install pipenv
          pipenv install --dev --system
      - name: Test with pytest
        run: |
          pipenv run flask translate compile
          pipenv run sh scripts/coverage.sh
      - name: Submit coverage data
        if: ${{ matrix.python-version == 3.9 && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v1
